config/routes.rb
Rails.application.routes.draw do
  # index
  get 'tasks', to: 'tasks#index', as: :tasks
  # new
  get 'tasks/new', to: 'tasks#new', as: :new
  post 'tasks', to: 'tasks#create'
  # show
  get 'tasks/:id', to: 'tasks#show', as: :task
  # edit
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch 'tasks/:id', to: 'tasks#update'
  # delete
  delete 'tasks/:id', to: 'tasks#delete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def delete
    @task = Task.find(params[:id])
    @task.delete
    redirect_to tasks_path
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>

<%= form_for(@task) do |t| %>
<%= t.label :title %>
<%= t.text_field :title %>
<%= t.label :details %>
<%= t.text_field :details %>
<%= t.label :completed %>
<%= t.check_box :completed %>
<%= t.submit %>
<% end %>

<br>

<%= link_to 'Back to list', tasks_path %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<ul>
  <% @tasks.each do |task| %>
  <li><%= link_to task.title, task_path(task[:id])%> <%= link_to 'Delete', task_path(task), method: :delete,
  data: { confirm: "Are you sure?" }%></li>
  <% end %>
</ul>

<br>

<h2><%= link_to 'Add a new task', new_path %></h2>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= form_for(@task) do |t| %>
<%= t.label :title %>
<%= t.text_field :title %>
<%= t.label :details %>
<%= t.text_field :details %>
<%= t.submit %>
<% end %>

<br>

<%= link_to 'Back to list', tasks_path %>

app/views/tasks/show.html.erb
<h1> <%= @task.title %> </h1>

<h2><%= link_to 'Edit this task', edit_path%></h2>

<h2><%= @task.details %></h2>

<% if @task.completed == true %>
<%= "This task is completed" %>
<% else %>
<%= "This task is not completed yet" %>
<% end %>

<br>

<%= link_to 'Back to list', tasks_path %>